#ifndef PLANNING_PLANNING_CHANNELS_H
#define PLANNING_PLANNING_CHANNELS_H

#define EXPLORATION_STATUS_CHANNEL "EXPLORATION_STATUS"
#define ARM_CMD_CHANNEL "ARM_CMD_CHANNEL"
#define BLOCK_LIST_CHANNEL "BLOCK_LIST_CHANNEL"

#endif // PLANNING_PLANNING_CHANNELS_H
